---

  - name: Install apache
    apt: name=apache2
    tags: apache

  - name: Enable apache modules
    apache2_module: name={{ item }}
    with_items:
      - proxy
      - proxy_http
      - rewrite
      - ssl
      - proxy_wstunnel
    tags: apache

  - name: Create ssl directory
    file: path=/etc/apache2/ssl state=directory
    when: not docker
    tags: apache

  - name: Install ssl certificate
    template: src=apache.crt.j2 dest=/etc/apache2/ssl/apache.crt
    when: not docker
    tags: apache
  
  - name: Install ssl private key
    template: src=apache.key.j2 dest=/etc/apache2/ssl/apache.key
    when: not docker
    tags: apache

  - name: Install comodo ca cert
    template: src=comodo.crt.j2 dest=/etc/apache2/ssl/comodo.crt
    when: not docker
    tags: apache

  - name: Configure apache proxy
    template: src=proxy.conf.j2 dest=/etc/apache2/conf-available/proxy.conf
    tags: apache
  
  - name: Configure apache ports
    template: src=ports.conf.j2 dest=/etc/apache2/ports.conf
    tags: apache

  - name: Configure apache ssl
    template: src=ssl.conf dest=/etc/apache2/mods-enabled/ssl.conf
    when: not docker
    tags: apache
  
  - name: Enable apache service
    service: name=apache2 state=started enabled=yes
    tags: apache

  - name: Enable proxy configuration
    command: a2enconf proxy
    notify: restart apache2
    tags: apache

  - template: src=supervisor-apached.conf.j2 dest=/etc/supervisor/conf.d/apached.conf
    when: docker
    tags: apache
