grits:
  image: grits
  container_name: grits
  ports:
    - "80:80"
    - "25:25"
    - "443:443"
  restart: always
  environment:
    - GIRDER_MONGO_URI=mongodb://172.30.2.123:27017/girder
    - MONGO_URL=mongodb://172.30.2.123:27017/
  volumes:
    - /mnt/mongo:/var/lib/mongo
    - /mnt/grits:/home/grits
    - /opt/grits-deploy-ansible:/opt/grits-deploy-ansible

