full-grits-api:
  image: full-grits-api
  container_name: full-grits-api
  ports:
    - "2222:22"
    - "80:80"
  restart: always
  environment:
    - placeholder=true
  volumes:
    - ~/container-mounted-volume:/var/lib/mongo


digital_infuzion:
  image: release_candidate
  container_name: document
  ports:
    - "80:80"
  restart: always
  environment:
    - placeholder=true
  volumes:
    - ~/container-mounted-volume:/var/lib/mongo
  command: bash /run.sh
