---

- hosts: prod
  roles:
    - common
    - postfix
    - apache
    - mongodb
    - node
    - s3restore
    - girder
    - grits-api
    - { role: jvm-nlp, sudo_user: "{{ grits_user }}" }
    - { role: diagnostic-dashboard, sudo_user: "{{ grits_user }}" }
    - { role: ansible-elasticsearch, tags: ["elasticsearch"] }
    - { role: elasticsearch-mongo-river, tags: ["elasticsearch"] }
  vars_files:
    - secure.prod.yml
  sudo: yes
