---

- hosts: prod
  pre_tasks:
  - name: Creating file at root to identify server type
    file: path=prod state=touch
  roles:
    #- { role: ansible-swapfile, swapfile_size: 16GB, swapfile_path: "/swapfile", sudo: yes, sudo_user: "root", tags: ["swapfile"] }
    - common
    - postfix
    - apache
    - { role: mongodb, tags: ["mongodb"] }
    - node
    - s3restore
    - { role: girder, tags: ["girder"] }
    - grits-api
    - download-classifier
    - { role: jvm-nlp }
    - { role: diagnostic-dashboard, tags: ["dashboard"] }
    - { role: ansible-elasticsearch, tags: ["elasticsearch"] }
    - { role: elasticsearch-mongo-river, tags: ["elasticsearch"] }
  vars_files:
    - secure.prod.yml
  sudo: yes
