---

- hosts: prod
  pre_tasks:
  - name: Remove old girder data from s3
    file: path={{ grits_user_home }}/dump state=absent
  roles:
    - s3restore
  vars_files:
    - secure.prod.yml
  sudo: yes
