---

- hosts: dev
  pre_tasks:
  - name: Creating file at root to identify server type
    file: path=dev state=touch
  roles:
    - common
    - postfix
    - apache
    - mongodb
    - node
    - s3restore
    - girder
    - { role: grits-api, sudo_user: "{{ grits_user }}" }
    - { role: jvm-nlp, sudo_user: "{{ grits_user }}" }
    - { role: diagnostic-dashboard, sudo_user: "{{ grits_user }}" }
    - { role: ansible-elasticsearch, tags: ["elasticsearch"] }
    - { role: elasticsearch-mongo-river, tags: ["elasticsearch"] }
  vars_files:
    - secure.yml
  sudo: yes
