---

- hosts: dev
  pre_tasks:
  - name: Creating file at root to identify server type
    file: path=dev state=touch
  roles:
    - { role: ansible-swapfile, swapfile_size: 8GB, swapfile_path: "/swapfile", sudo: yes, sudo_user: "root", tags: ["swapfile"] }
    - common
    - postfix
    - apache
    - mongodb
    - node
    - s3restore
    - { role: girder, tags: ["girder"] }
    - { role: grits-api, tags: ["gritsapi"] }
    - { role: jvm-nlp, tags: ["jvmnlp"] }
    - { role: diagnostic-dashboard, tags: ["dashboard"] }
    - { role: ansible-elasticsearch, tags: ["elasticsearch"] }
    - { role: elasticsearch-mongo-river, tags: ["elasticsearch"] }
  vars_files:
    - secure.yml
  sudo: yes
