---
- lineinfile: dest=/etc/mongod.conf line="port={{mongo_port}}" regexp="^port(\s*)="
- lineinfile: dest=/etc/mongod.conf line="bind_ip={{mongo_host}}" regexp="^bind_ip(\s*)="
- lineinfile: dest=/etc/mongod.conf line="replSet=rs0" regexp="^replSet(\s*)="
- lineinfile: dest=/etc/mongod.conf line="oplogSize=1024" regexp="^oplogSize(\s*)="

- name: Restart mongod
  service: name=mongod state=restarted

- name: Waiting for mongo restart
  wait_for: port={{mongo_port}} delay=2

- command: mongo --eval 'rs.initiate({"_id":"rs0","members":[{"_id":1,"host":"{{mongo_host}}:{{mongo_port}}"}]})'

- name: Waiting for elasticsearch restart
  wait_for: port=9200 delay=2

- name: Write river config
  template: src=riverConfig.j2 dest=/etc/riverConfig.json mode=0755
  register: riverConfig
  
- name: Write girder item mapping config
  template: src=girderMappingConfig.j2 dest=/etc/girderMappingConfig.json mode=0755
  register: girderMappingConfig

- name: Dump all elasticsearch data
  command: curl -XDELETE http://localhost:9200/_all 
  when: riverConfig.changed or girderMappingConfig.changed

- name: Creating girder item index
  command: curl -XPUT 'localhost:9200/item_index/'
  when: riverConfig.changed or girderMappingConfig.changed
      
- name: Configure mongodb elasticsearch river
  command: curl -XPUT "localhost:9200/item_index/girder_item/_mapping" -d @/etc/girderMappingConfig.json
  when: riverConfig.changed or girderMappingConfig.changed

- name: Configure mongodb elasticsearch river
  command: curl -XPUT "localhost:9200/_river/mongo_girder_items/_meta" -d @/etc/riverConfig.json
  when: riverConfig.changed or girderMappingConfig.changed

- name: Restarting Elasticsearch
  service: name=elasticsearch state=restarted

- name: Waiting for elasticsearch restart
  wait_for: port=9200 delay=10

- name: |
    Get elasticsearch index status 
    (On the first run the index will be incomplete because there is lots of bg processing left to do)
  command: curl 'http://localhost:9200/item_index/_status'
  register: item_index_status
#- debug: var={{(item_index_status.stdout|from_json).indices.item_index.docs.num_docs}}
- name: Test elasticsearch index
  assert:
    that:
      - "(item_index_status.stdout|from_json).indices.item_index.docs.num_docs > 0"
