---
- name: Ensure postfix is installed (RedHat).
  yum: pkg=postfix state=installed
  when: ansible_os_family == 'RedHat'

- name: Ensure postfix is installed (Debian).
  apt: pkg=postfix state=installed
  when: ansible_os_family == 'Debian'

- name: Ensure postfix is started and enabled at boot.
  service: name=postfix state=started enabled=yes
  when: not docker

- template: src=postfix.conf.j2 dest=/etc/supervisor/conf.d/postfix.conf
  when: docker

- #service: name=supervisor state=restarted
  when: docker

