---

  - name: Install apt dependencies
    apt: name={{ item }}
    with_items:
      - gfortran
      - libopenblas-dev
      - liblapack-dev
      - lib32z1-dev
      - zip
      - unzip
      - libxml2-dev
      - libxslt1-dev
    sudo: yes
    sudo_user: root

  - name: Copy grits-api
    copy: src=grits-api/ dest={{ grits_api_prefix }}-source
    notify: restart grits api group
    register: grits_api
  
  - name: Remove grits api directory
    file: path={{ grits_api_prefix }} state=absent
    sudo: yes
    sudo_user: root
    when: grits_api.changed
    
  - name: Replace grits-api deployment directory with the updated source
    command: cp -r {{ grits_api_prefix }}-source {{ grits_api_prefix }}
    when: grits_api.changed
  
  - name: Configure grits-api
    template: src=config.py.j2 dest={{ grits_api_prefix }}/config.py

  - name: Install requirements
    pip: requirements={{ grits_api_prefix }}/requirements.txt virtualenv={{ grits_env }}

  # This should be added to requirements.txt
  - name: Install nose
    pip: name=nose virtualenv={{ grits_env }}

  - name: Download nltk data
    shell: "{{ grits_env }}/bin/python -c \"import nltk; nltk.download('{{ item }}')\" && echo done > .nltk_{{ item }}_downloaded"
    args:
      chdir: /home/{{ grits_user }}
      creates: /home/{{ grits_user }}/.nltk_{{ item }}_downloaded
    with_items:
      - maxent_ne_chunker
      - maxent_treebank_pos_tagger
      - words
      - punkt
    sudo: yes
    sudo_user: "{{ grits_user }}"
    notify: restart grits api group

  - name: Copy annie
    copy: src=annie/ dest={{ annie_prefix }}
    notify: restart grits api group

  # This reinstalls annie on every deployment (it only takes a few seconds tho).
  # We tried using the pip module and creating a install file, but these create
  # complications when annie is updated.
  - name: Install annie
    shell: "{{ grits_env }}/bin/python setup.py install"
    args:
      chdir: "{{ annie_prefix }}"

  - name: Download geonames data
    get_url: url=http://download.geonames.org/export/dump/allCountries.zip dest={{ annie_prefix }}/allCountries.zip

  - name: Extract geonames zip
    unarchive:
      src: "{{ annie_prefix }}/allCountries.zip"
      dest: "{{ annie_prefix }}"
      copy: no
      creates: "{{ annie_prefix }}/allCountries.txt"

  - name: Import geonames database
    shell: "{{ grits_env }}/bin/python mongo_import_geonames.py --mongo_url {{ mongo_url }} && echo done > .geonames.imported"
    args:
      chdir: "{{ annie_prefix }}"
      # This approach might cause annie updates to trigger unnecessairy geonames updates.
      creates: "{{ annie_prefix }}/.geonames.imported"
    sudo: yes
    # This seems to prevent us from writing .geonames.imported
    # sudo_user: "{{ grits_user }}"

  - name: Check that classifier has been trained
    stat: path="{{ grits_api_prefix }}/classifier.p"
    register: classifier_data
  
  - name: Restart tomcat7 to reclaim memory
    service: name=tomcat7 state=restarted enabled=yes
    sudo: yes
    sudo_user: root
    when: not classifier_data.stat.exists
    ignore_errors: yes

  - name: restart grits api group to reclaim memory
    supervisorctl: name="gritsapigroup:" state=restarted
    sudo: yes
    sudo_user: root
    when: not classifier_data.stat.exists
    ignore_errors: yes
  - name: Training
    shell: "{{ grits_env }}/bin/python train.py"
    args:
      chdir: "{{ grits_api_prefix }}"
      creates: "{{ grits_api_prefix }}/classifier.p"
    tags:
      - train
    notify: restart grits api group

  - name: Load mongo keywords
    shell: "{{ grits_env }}/bin/python mongo_import_keywords.py"
    args:
      chdir: "{{ grits_api_prefix }}"

  - name: Install supervisord configs
    template: src={{ item }}.conf.j2 dest=/etc/supervisor/conf.d/{{ item }}.conf
    notify: reload supervisor
    sudo: yes
    sudo_user: root
    with_items:
      - celeryd
      - gritsapid

  - name: Install flower supervisord config
    template: src=flowerd.conf.j2 dest=/etc/supervisor/conf.d/flowerd.conf
    notify: reload supervisor
    sudo: yes
    sudo_user: root
    when: flower_password != ""

  - name: Copy cron script
    template:
      src: diagnose_girder_HM_articles.j2
      dest: "{{ cron_prefix }}/diagnose_girder_HM_articles"
      group: "{{ grits_group }}"
      owner: "{{ grits_user }}"
      mode: 0755

  - name: Install healthmap diagnosis cron job
    cron:
      name: "Diagnose healthmap articles"
      user: "{{ grits_user }}"
      job: "{{ cron_prefix }}/diagnose_girder_HM_articles"
      day: 26
      hour: 3
      minute: 0
    when: run_cron_jobs

  - name: Creating cron job that restarts processes in order to free memory
    cron:
      name: "Restart processes"
      user: "root"
      job: "service tomcat7 restart ; supervisorctl restart gritsapigroup:celery_diagnose"
      hour: 3
      minute: 0
    when: run_cron_jobs
