---

  - name: Install apt dependencies
    apt: name={{ item }}
    with_items:
      - gfortran
      - libopenblas-dev
      - liblapack-dev
      - lib32z1-dev
      - zip
      - unzip
      - libxml2-dev
      - libxslt1-dev
    sudo: yes
    sudo_user: root

  - name: Copy grits-api
    copy: src=grits-api/ dest={{ grits_api_prefix }}

  - name: Configure grits-api
    template: src=config.py.j2 dest={{ grits_api_prefix }}/config.py

  - name: Install requirements
    pip: requirements={{ grits_api_prefix }}/requirements.txt virtualenv={{ grits_api_prefix }}/env

  # This should be added to requirements.txt
  - name: Install nose
    pip: name=nose virtualenv={{ grits_api_prefix }}/env

  - name: Download nltk data
    command: "{{ grits_api_prefix }}/env/bin/python -c \"import nltk; nltk.download('{{ item }}')\""
    with_items:
      - maxent_ne_chunker
      - maxent_treebank_pos_tagger
      - words
      - punkt

  - name: Download geonames data
    get_url: url=http://download.geonames.org/export/dump/allCountries.zip dest={{ grits_api_prefix }}/allCountries.zip

  - name: Extract geonames zip
    unarchive:
      src: "{{ grits_api_prefix }}/allCountries.zip"
      dest: "{{ grits_api_prefix }}/diagnosis"
      copy: no
      creates: "{{ grits_api_prefix }}/diagnosis/allCountries.txt"
  
  - name: Import geonames database
    shell: "{{ grits_api_prefix }}/env/bin/python mongo_import_geonames.py && echo done > geonames.imported"
    args:
      chdir: "{{ grits_api_prefix }}/diagnosis"
      creates: "{{ grits_api_prefix }}/diagnosis/geonames.imported"
    sudo: yes
    sudo_user: "{{ grits_user }}"
  

  - name: Copy annie
    copy: src=annie/ dest={{ annie_prefix }}

  - name: Install annie
    command: "{{ grits_api_prefix }}/env/bin/python setup.py install chdir={{ annie_prefix }}"

  # This command fails at the end
  - name: Training
    command: "{{ grits_api_prefix }}/env/bin/python train.py"
    args:
      chdir: "{{ grits_api_prefix }}"
      creates: "{{ grits_api_prefix }}/keyword_sets.p"
    ignore_errors: yes
    tags:
      - train

  - name: Install celery supervisord config
    template: src=celeryd.conf.j2 dest=/etc/supervisor/conf.d/celeryd.conf
    notify: reload supervisor
    sudo: yes
    sudo_user: root

  - name: Install flask supervisord config
    template: src=flaskd.conf.j2 dest=/etc/supervisor/conf.d/flaskd.conf
    notify: reload supervisor
    sudo: yes
    sudo_user: root

  - name: Copy cron script
    template:
      src: diagnose_girder_HM_articles.j2
      dest: "{{ cron_prefix }}/diagnose_girder_HM_articles"
      group: "{{ grits_group }}"
      owner: "{{ grits_user }}"
      mode: 0755

  - name: Install healthmap diagnosis cron job
    cron:
      name: "Diagnose healthmap articles"
      user: "{{ grits_user }}"
      job: "{{ cron_prefix }}/diagnose_girder_HM_articles"
      hour: 3
      minute: 0
    when: run_cron_jobs
