---
- file: path=/home/grits/classifiers/ state=directory  owner={{ grits_user }}

- name: Update classifier data from s3
  command: "aws s3 sync s3://classifier-data/classifiers/ /home/grits/classifiers/"
  sudo: yes
  sudo_user: "{{ grits_user }}"
  when: girder_data_access_key is defined

- name: Find newest classifier directory
  # The directory timestamps are not preserved on AWS, so the file timestamps are used.
  shell: "ls -t /home/grits/classifiers/*/*.p | head -1 | xargs dirname"
  register: newest_classifier_dir
  sudo: yes

- set_fact: classifier_path="{{newest_classifier_dir.stdout}}"

- set_fact: classifier_path="/home/grits/classifiers/{{classifier_id}}"
  when: classifier_id is defined and classifier_id != "newest"

- name: Setting current classifier to the latest
  file: src={{classifier_path}} dest={{ grits_api_prefix }}/current_classifier state=link force=yes
  register: classifier_symlink
  sudo: true
  notify: restart grits api group

- name: Loading mongo keywords used for annotation
  shell: "{{ grits_env }}/bin/python mongo_import_keywords.py"
  args:
    chdir: "{{ grits_api_prefix }}"
  when: classifier_symlink.changed
