---
- file: path=/home/grits/classifiers/ state=directory  owner={{ grits_user }}

- name: Update classifier data from s3
  command: "aws s3 sync s3://classifier-data/classifiers/ /home/grits/classifiers/"
  sudo: yes
  sudo_user: "{{ grits_user }}"
  when: girder_data_access_key is defined

- shell: "ls -t /home/grits/classifiers/ | head -1"
  register: newest_classifier
  sudo: yes

- set_fact: classifier_path="/home/grits/classifiers/{{classifier_id | default(newest_classifier.stdout)}}"

- name: Setting current classifier to the latest
  file: src={{classifier_path}} dest={{ grits_api_prefix }}/current_classifier state=link force=yes
  register: classifier_symlink
  sudo: true

- name: Loading mongo keywords used for annotation
  shell: "{{ grits_env }}/bin/python mongo_import_keywords.py"
  args:
    chdir: "{{ grits_api_prefix }}"
  when: classifier_symlink.changed
