---

  - name: restart celery
    supervisorctl: name={{ item }} state=restarted
    with_items:
      - celery_process
      - celery_diagnose
    sudo: yes
    sudo_user: root
  
  - name: restart flask
    supervisorctl: name=flask state=restarted
    sudo: yes
    sudo_user: root
