---

- name: Install common packages from apt
  apt: pkg={{item}} state=installed update_cache=yes
  sudo: True
  with_items:
    - git
    - make
    - python-pip
    - python-dev
    - supervisor

- name: Install global python modules
  pip: name={{item}}
  sudo: True
  with_items:
    - awscli
    - virtualenv

- name: Create grits group
  user: name={{ grits_group }}

- name: Create grits user
  user: name={{ grits_user }} group={{ grits_group }} shell=/bin/bash

- name: Create grits environment configuration
  template: src=config.j2 dest=/home/{{ grits_user }}/grits_config group={{ grits_group }} owner={{ grits_user }}

- name: Create cron script directory
  file: path={{ cron_prefix }} group={{ grits_group }} owner={{ grits_user }} state=directory

- name: Create cron log directory
  file: path={{ cron_logs }} group={{ grits_group }} owner={{ grits_user }} state=directory
